services:

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  admin-service:
    build: ./admin-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - api-gateway

  billing-service:
    build: ./billing-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - api-gateway

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - api-gateway

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - api-gateway

  order-service:
    build: ./order-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - api-gateway

  payment-service:
    build: ./payment-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - api-gateway

  notification-service:
    build: ./notification-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - api-gateway

  prescription-service:
    build: ./prescription-service
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
      - api-gateway
